name: range_fix
description: A workaround for the Range.getClientRects bug in Chrome.
version: 0.1.1
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/range_fix

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  browser: any
  color: any
  test: '>=0.12.0 <0.13.0'
